import "react-toastify/dist/ReactToastify.css";
import "../globals.css";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import { QueryProvider } from "@/providers/query";

export const metadata: Metadata = {
  title: "Chef finder",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  }
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "800"],
});

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <QueryProvider>
            {children}
            <ToastContainer
              style={{
                right: "0",
              }}
              theme="colored"
            />
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
